apiVersion: apps/v1
kind: Deployment
metadata:
  name:  queue-listener
  labels:
    app:  queue-listener
spec:
  selector:
    matchLabels:
      app: queue-listener
  template:
    metadata:
      labels:
        app:  queue-listener
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: queue-listener
      containers:
      - name:  queue-listener
        image:  davydrudenkoua/queue-listener:latest
        resources:
          requests:
            cpu: 300m
            memory: 300Mi
          limits:
            cpu: 300m
            memory: 300Mi
      imagePullSecrets:
        - name: queue-listener-registry-secret